/**
 * data.js - Generated by Admin Panel
 * Generated at: 2026-07-04T16:56:32.527Z
 *
 * DO NOT EDIT MANUALLY unless you know what you're doing.
 * Use admin.html to add new content, then export again.
 *
 * File structure:
 * - collegesData: array of colleges
 * - Each college has: id, name (ar/en/fr), icon, color, specializations[]
 * - Each specialization has: id, name (ar/en/fr), courses[]
 * - Each course has: id, name (ar/en/fr), instructors[], files[]
 * - Each file has: id, title (ar/en/fr), type (summary/testbank), preparedBy, path
 *
 * NOTE: Actual PDF files must be placed manually in assets/files/
 */

const collegesData = [
  {
    "id": "business",
    "name": {
      "ar": "كلية الأعمال",
      "en": "College of Business",
      "fr": "Faculté des Affaires"
    },
    "icon": "💼",
    "color": "#4f46e5",
    "specializations": [
      {
        "id": "business-admin",
        "name": {
          "ar": "إدارة الأعمال",
          "en": "Business Administration",
          "fr": "Gestion des Affaires"
        },
        "courses": [
          {
            "id": "business-admin-1783172905544",
            "name": {
              "ar": "نظم دعم القرار",
              "en": "Decision Support Systems (DSS)",
              "fr": "Systèmes d'aide à la décision (SAD)"
            },
            "instructors": [
              {
                "ar": "يسار شطناوي",
                "en": "يسار شطناوي",
                "fr": "يسار شطناوي"
              }
            ],
            "files": [
              {
                "id": "file-1783172905544-1",
                "title": {
                  "ar": "نظم دعم القرار – د. يسار شطناوي – ميد، كويز، فاينل",
                  "en": "Decision Support Systems – Dr. Yasar Shatnawi – Midterm, Quiz, Final",
                  "fr": "Systèmes d'aide à la décision – Dr Yasar Shatnawi – Examen de mi-session, Quiz, Examen final"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1KGuPmbXh96FG2YgsT-PM9vsZ60kn7BWK/view?usp=drive_link"
              },
              {
                "id": "file-1783172905544-2",
                "title": {
                  "ar": "تلخيص الفصل الثاني + واجب مادة نظم دعم القرار للدكتورة يسار شطناوي",
                  "en": "Summary of Chapter 2 + assignment of Decision Support Systems course by Dr. Yasar Shatnawi",
                  "fr": "Résumé du chapitre 2 + devoir du cours des systèmes d’aide à la décision du Dr Yasar Shatnawi"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1mU6iEXPUeNg42hFiphwCIbXTXam_WbRk/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783173156321",
            "name": {
              "ar": "نظرية المنظمة",
              "en": "Organization Theory",
              "fr": "Théorie des organisations"
            },
            "instructors": [
              {
                "ar": "الهام الفاعوري",
                "en": "الهام الفاعوري",
                "fr": "الهام الفاعوري"
              }
            ],
            "files": [
              {
                "id": "file-1783173156321-1",
                "title": {
                  "ar": "ميد + كويز + فاينال نظرية المنظمة – د. إلهام الفاعوري",
                  "en": "Midterm + Quiz + Final – Organization Theory – Dr. Ilham Al-Faouri",
                  "fr": "Mi-session + Quiz + Examen final – Théorie des organisations – Dr Ilham Al-Faouri"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1ZXMg24o7ilvLD8j1seRdrvtpw0Y_Q952/view?usp=drive_link"
              },
              {
                "id": "file-1783173156321-2",
                "title": {
                  "ar": "تلخيص نظرية المنظمة – د. إلهام الفاعوري – الفصول 1 إلى 5",
                  "en": "Summary of Organization Theory – Dr. Ilham Al-Faouri – Chapters 1 to 5",
                  "fr": "Résumé de la théorie des organisations – Dr Ilham Al-Faouri – chapitres 1 à 5"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1WSQaf_wtKFJrseZndgO2yz3GT3rK6l3Q/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783173962569",
            "name": {
              "ar": "منهجية البحث العلمي في الأعمال",
              "en": "Business Research Methodology",
              "fr": "Méthodologie de la recherche en gestion"
            },
            "instructors": [
              {
                "ar": "محمد نوايسة",
                "en": "محمد نوايسة",
                "fr": "محمد نوايسة"
              },
              {
                "ar": "محمد نواصرة",
                "en": "محمد نواصرة",
                "fr": "محمد نواصرة"
              }
            ],
            "files": [
              {
                "id": "file-1783173962569-1",
                "title": {
                  "ar": "ميد + كويز مادة منهجية البحث العلمي – د. محمود نوايسة",
                  "en": "Midterm + Quiz – Business Research Methodology – Dr. Mahmoud Nwaisah",
                  "fr": "Mi-session + Quiz – Méthodologie de la recherche en gestion – Dr Mahmoud Nwaisah"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1TvmRq4Yx0TlrQII2kCyNnnKY0Bv6ognj/view?usp=drive_link"
              },
              {
                "id": "file-1783173962569-2",
                "title": {
                  "ar": "بنك أسئلة منهجية البحث العلمي",
                  "en": "Research Methodology Test Bank",
                  "fr": "Banque de questions de méthodologie de recherche"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1Sv_2v60i3TKprOeIal28D_B57J1XNRdo/view?usp=drive_link"
              },
              {
                "id": "file-1783173962569-3",
                "title": {
                  "ar": "فاينال مادة منهجية البحث العلمي – د. محمد مصاروة",
                  "en": "Final Exam – Business Research Methodology – Dr. Mohammad Masarwa",
                  "fr": "Examen final – Méthodologie de la recherche en gestion – Dr Mohammad Masarwa"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/14UCubwvr96WDNXJM06Yr0cZzomtn8HZL/view?usp=drive_link"
              },
              {
                "id": "file-1783173962569-4",
                "title": {
                  "ar": "بنك أسئلة",
                  "en": "Test Bank",
                  "fr": "Banque de questions"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/15eqokBXFRQujN1pT-SzuwjT9ckJ7F5va/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783174218963",
            "name": {
              "ar": "مبادئ نظم المعلومات الإدارية",
              "en": "Principles of Management Information Systems (MIS)",
              "fr": "Principes des systèmes d'information de gestion"
            },
            "instructors": [
              {
                "ar": "محمود النوايسة",
                "en": "محمود النوايسة",
                "fr": "محمود النوايسة"
              },
              {
                "ar": "يسار الشطناوي",
                "en": "يسار الشطناوي",
                "fr": "يسار الشطناوي"
              }
            ],
            "files": [
              {
                "id": "file-1783174218963-1",
                "title": {
                  "ar": "تلخيص امتحان منتصف الفصل لمادة نظم المعلومات الإدارية (MIS) – د. يسار شطناوي",
                  "en": "Midterm summary of Management Information Systems (MIS) – Dr. Yasar Shatnawi",
                  "fr": "Résumé du partiel des systèmes d'information de gestion (MIS) – Dr Yasar Shatnawi"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://docs.google.com/document/d/1sMzqNxzPqo5KV1oqrt-grTJk_YWyS8_i/edit?usp=drive_link&ouid=109869346135494350780&rtpof=true&sd=true"
              },
              {
                "id": "file-1783174218963-2",
                "title": {
                  "ar": "تلخيص امتحان منتصف الفصل لمادة نظم المعلومات الإدارية (MIS) – د. يسار شطناوي",
                  "en": "Midterm summary of Management Information Systems (MIS) – Dr. Yasar Shatnawi",
                  "fr": "Résumé du partiel des systèmes d'information de gestion (MIS) – Dr Yasar Shatnawi"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1tepGKziKe_hqpxWyqhCvuAjyK95fb8hy/view?usp=drive_link"
              },
              {
                "id": "file-1783174218963-3",
                "title": {
                  "ar": "نظم المعلومات الإدارية (MIS) – د. محمود نوايسة – الفصول 1 إلى 6",
                  "en": "Management Information Systems (MIS) – Dr. Mahmoud Nwaisah – Chapters 1 to 6",
                  "fr": "Systèmes d'information de gestion (MIS) – Dr Mahmoud Nwaisah – chapitres 1 à 6"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1iLGKM2_yW_JgPgKYlKrROxhx91JKGF7x/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783174500779",
            "name": {
              "ar": "مبادئ التسويق",
              "en": "Principles of Marketing",
              "fr": "Principes du marketing"
            },
            "instructors": [
              {
                "ar": "ايمان الملكاوي",
                "en": "ايمان الملكاوي",
                "fr": "ايمان الملكاوي"
              }
            ],
            "files": [
              {
                "id": "file-1783174500779-1",
                "title": {
                  "ar": "امتحان نهائي مادة مبادئ التسويق – د. إيمان ملكاوي",
                  "en": "Final exam of Principles of Marketing – Dr. Iman Malkawi",
                  "fr": "Examen final de Principes du marketing – Dr Iman Malkawi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1eJwdYsnm-KF3yVQjFcYarMlWViXM-HFz/view?usp=drive_link"
              },
              {
                "id": "file-1783174500779-2",
                "title": {
                  "ar": "بنك أسئلة مبادئ التسويق – الفصل الأول",
                  "en": "Marketing Principles Test Bank – Chapter 1",
                  "fr": "Banque de questions de principes du marketing – chapitre 1"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1d_oUv4LevHZLIS1IASAUvJLm-Ivn7EiW/view?usp=drive_link"
              },
              {
                "id": "file-1783174500779-3",
                "title": {
                  "ar": "كتاب مادة",
                  "en": "Course textbook",
                  "fr": "Manuel de cours"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1gIHq38fM-OanC042YnSysBaTcwE2PLNt/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783175048963",
            "name": {
              "ar": "مبادئ التأمين",
              "en": "Principles of Insurance",
              "fr": "Principes de l’assurance"
            },
            "instructors": [
              {
                "ar": "فراس الرواشدة",
                "en": "فراس الرواشدة",
                "fr": "فراس الرواشدة"
              }
            ],
            "files": [
              {
                "id": "file-1783175048963-1",
                "title": {
                  "ar": "امتحان منتصف الفصل + امتحان نهائي لمادة مبادئ التأمين – د. فراس الرواشدة",
                  "en": "Midterm + Final exam – Principles of Insurance – Dr. Firas Al-Rawashdeh",
                  "fr": "Examen de mi-session + examen final – Principes de l’assurance – Dr Firas Al-Rawashdeh"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1k0VDT1H--3TrRyCoUtYCaqJU0qKtV1ns/view?usp=drive_link"
              },
              {
                "id": "file-1783175048963-2",
                "title": {
                  "ar": "ملخص مادة مبادئ التأمين – ميد + فاينل – د. فراس الرواشدة",
                  "en": "Insurance Principles summary – midterm & final – Dr. Firas Al-Rawashdeh",
                  "fr": "Résumé des principes de l’assurance – mi-session et examen final – Dr Firas Al-Rawashdeh"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1HaiEi2IZMurbwXLlfwOvLUSmroR9NiAk/view?usp=drive_link"
              },
              {
                "id": "file-1783175048963-3",
                "title": {
                  "ar": "اختبارات قصيرة لمادة مبادئ التأمين",
                  "en": "Insurance Principles quizzes",
                  "fr": "Quiz des principes de l’assurance"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1GEU0D0QQKKggIm1_T51PvRn556Ghkhf_/view?usp=drive_link"
              },
              {
                "id": "file-1783175048963-4",
                "title": {
                  "ar": "امتحان نهائي مادة التأمين – د. فراس",
                  "en": "Final exam – Insurance course – Dr. Firas",
                  "fr": "Examen final – cours d’assurance – Dr Firas"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/11BS0yBCjV4g5azcSbZDzUMOuPaNIAOLU/view?usp=drive_link"
              },
              {
                "id": "file-1783175048963-5",
                "title": {
                  "ar": "تلخيص الفصل الثاني: التأمين والمخاطر",
                  "en": "Summary of Chapter 2: Insurance and Risk",
                  "fr": "Résumé du chapitre 2 : Assurance et risque"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1LstSNtuBktOxpX-xr4exooRPQEeKjUNS/view?usp=drive_link"
              },
              {
                "id": "file-1783175048963-6",
                "title": {
                  "ar": "تلخيص الفصل الأول: المخاطر والتأمين",
                  "en": "Summary of Chapter 1: Risk and Insurance",
                  "fr": "Résumé du chapitre 1 : Risque et assurance"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1yNfM_GcWs4vOykD0mavP6cA8JtzGIR5i/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783175390813",
            "name": {
              "ar": "مبادئ إدارة الأعمال",
              "en": "Principles of Business Administration",
              "fr": "Principes de la gestion des entreprises"
            },
            "instructors": [
              {
                "ar": "يسار الشطناوي",
                "en": "يسار الشطناوي",
                "fr": "يسار الشطناوي"
              }
            ],
            "files": [
              {
                "id": "file-1783175390813-1",
                "title": {
                  "ar": "تلخيص الفصول 1 و2 و4 و17 + بنك أسئلة",
                  "en": "Summary of Chapters 1, 2, 4, and 17 + Test Bank",
                  "fr": "Résumé des chapitres 1, 2, 4 et 17 + banque de questions"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1eOlb_r5DE4og_jSENeEW1yHjcdl9dLHl/view?usp=drive_link"
              },
              {
                "id": "file-1783175390813-2",
                "title": {
                  "ar": "مبادئ الإدارة – الفصل الأول والثاني",
                  "en": "Principles of Management – Chapters 1 and 2",
                  "fr": "Principes de gestion – chapitres 1 et 2"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1fogMzOkwkxgYDlihQgKYxHcVTZRC98rX/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783175601344",
            "name": {
              "ar": "تطبيقات الحاسوب في الأعمال",
              "en": "Computer Applications in Business",
              "fr": "Applications de l’informatique en entreprise"
            },
            "instructors": [],
            "files": [
              {
                "id": "file-1783175601344-1",
                "title": {
                  "ar": "مجموعة كبيرة من الملفات",
                  "en": "Large collection of files",
                  "fr": "Grand ensemble de fichiers"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/drive/folders/1n_UoZY1dyHDwvkRRQvdb3jTwu9Y7ZrhF?usp=sharing"
              }
            ]
          },
          {
            "id": "business-admin-1783175798833",
            "name": {
              "ar": "تشريعات تجارية",
              "en": "Commercial Legislation",
              "fr": "Législation commerciale"
            },
            "instructors": [],
            "files": [
              {
                "id": "file-1783175798833-1",
                "title": {
                  "ar": "مجموعة من الملخصات بملف واحد",
                  "en": "A collection of summaries in one file",
                  "fr": "Un ensemble de résumés dans un seul fichier"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/drive/folders/1kcj79HRAPBWRC6K4QErr-ViDkzycmLAN?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783176341636",
            "name": {
              "ar": "بحوث العمليات",
              "en": "Operations Research",
              "fr": "Recherche opérationnelle"
            },
            "instructors": [
              {
                "ar": "محمد مصاروه",
                "en": "محمد مصاروه",
                "fr": "محمد مصاروه"
              },
              {
                "ar": "صدام الوادي",
                "en": "صدام الوادي",
                "fr": "صدام الوادي"
              }
            ],
            "files": [
              {
                "id": "file-1783176341636-1",
                "title": {
                  "ar": "امتحان منتصف الفصل + كويز 1 و2 و3 لمادة بحوث العمليات – د. محمد مصاروة",
                  "en": "Midterm + Quizzes 1, 2, 3 – Operations Research – Dr. Mohammad Masarwa",
                  "fr": "Mi-session + quiz 1, 2 et 3 – Recherche opérationnelle – Dr Mohammad Masarwa"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1JacnOFmMUwBzNKKb0MB2iNS2xxnwLrng/view?usp=drive_link"
              },
              {
                "id": "file-1783176341636-2",
                "title": {
                  "ar": "كويز + امتحان منتصف الفصل لمادة بحوث العمليات – د. صدام الوادي",
                  "en": "Quizzes + Midterm – Operations Research – Dr. Saddam Al-Wadi",
                  "fr": "Quiz + examen de mi-session – Recherche opérationnelle – Dr Saddam Al-Wadi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1mNburXl5QmOBr4d_Tlqfx_LcQFUsbkuf/view?usp=drive_link"
              },
              {
                "id": "file-1783176341636-3",
                "title": {
                  "ar": "امتحان منتصف الفصل لمادة بحوث العمليات – د. محمد مصاروة",
                  "en": "Midterm exam for Operations Research – Dr. Mohammad Masarwa",
                  "fr": "Examen de mi-session en recherche opérationnelle – Dr Mohammad Masarwa"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/10hd-uPB3QDL-TJmHqhSIrecjhVC6Y-LR/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783176627338",
            "name": {
              "ar": "السلوك التنظيمي",
              "en": "Organizational Behavior",
              "fr": "Comportement organisationnel"
            },
            "instructors": [
              {
                "ar": "الهام الفاعوري",
                "en": "الهام الفاعوري",
                "fr": "الهام الفاعوري"
              }
            ],
            "files": [
              {
                "id": "file-1783176627338-1",
                "title": {
                  "ar": "تلخيص مادة السلوك التنظيمي – الفصول 1 و2 و3 – د. إلهام الفاعوري",
                  "en": "Organizational Behavior summary – Chapters 1, 2, 3 – Dr. Ilham Al-Faouri",
                  "fr": "Résumé du comportement organisationnel – chapitres 1, 2, 3 – Dr Ilham Al-Faouri"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/11o1PDmTrrhUriIQbc2AB-HLQa6dxRVJ4/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783176833534",
            "name": {
              "ar": "الريادية في الأعمال",
              "en": "Entrepreneurship in Business",
              "fr": "Entrepreneuriat en affaires"
            },
            "instructors": [
              {
                "ar": "يسار شطناوي",
                "en": "يسار شطناوي",
                "fr": "يسار شطناوي"
              },
              {
                "ar": "ايمان ملكاوي",
                "en": "ايمان ملكاوي",
                "fr": "ايمان ملكاوي"
              }
            ],
            "files": [
              {
                "id": "file-1783176833534-1",
                "title": {
                  "ar": "امتحان منتصف الفصل لمادة الريادية في الأعمال – د. إيمان ملكاوي",
                  "en": "Midterm exam – Entrepreneurship in Business – Dr. Iman Malkawi",
                  "fr": "Examen de mi-session – Entrepreneuriat en affaires – Dr Iman Malkawi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1ug_xZLm18-p-y6ay6mxCJ2aVpWdxHUWe/view?usp=drive_link"
              },
              {
                "id": "file-1783176833534-2",
                "title": {
                  "ar": "ملخص مادة الريادية في الأعمال – د. يسار شطناوي",
                  "en": "Entrepreneurship in Business summary – Dr. Yasar Shatnawi",
                  "fr": "Résumé de l’entrepreneuriat en affaires – Dr Yasar Shatnawi"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1VvduNGFPo9MGs0NH0VLD28VaLl3DoDLA/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783176995499",
            "name": {
              "ar": "الحاكمية المؤسسية",
              "en": "Corporate Governance",
              "fr": "Gouvernance d’entreprise"
            },
            "instructors": [],
            "files": [
              {
                "id": "file-1783176995499-1",
                "title": {
                  "ar": "امتحان منتصف الفصل لمادة الحاكمية المؤسسية",
                  "en": "Corporate Governance midterm exam",
                  "fr": "Examen de mi-session en gouvernance d’entreprise"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1UTQD_MtnuNwObnrubc3hXkUFz9WEzYXA/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783177198728",
            "name": {
              "ar": "الأعمال الإلكترونية",
              "en": "Electronic Business (E-Business)",
              "fr": "Commerce électronique / e-business"
            },
            "instructors": [
              {
                "ar": "ايمان ملكاوي",
                "en": "ايمان ملكاوي",
                "fr": "ايمان ملكاوي"
              }
            ],
            "files": [
              {
                "id": "file-1783177198727-1",
                "title": {
                  "ar": "ملخص مادة الأعمال الإلكترونية – د. إيمان ملكاوي",
                  "en": "Electronic Business summary – Dr. Iman Malkawi",
                  "fr": "Résumé du commerce électronique – Dr Iman Malkawi"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1nlRELxGmDXQhk4GzDOAQuJMajrGOpQtw/view?usp=drive_link"
              },
              {
                "id": "file-1783177198727-2",
                "title": {
                  "ar": "امتحان منتصف الفصل + امتحان نهائي لمادة الأعمال الإلكترونية – د. إيمان ملكاوي",
                  "en": "Midterm + Final exam – Electronic Business – Dr. Iman Malkawi",
                  "fr": "Examen de mi-session + examen final – Commerce électronique – Dr Iman Malkawi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1jCd4evhKWpTkusbGtyjDFfBXYbI5oJ9s/view?usp=drive_link"
              },
              {
                "id": "file-1783177198727-3",
                "title": {
                  "ar": "تلخيص الفصلين 2 و3 من مادة الأعمال الإلكترونية – د. إيمان ملكاوي",
                  "en": "Summary of Chapters 2 and 3 – Electronic Business – Dr. Iman Malkawi",
                  "fr": "Résumé des chapitres 2 et 3 – Commerce électronique – Dr Iman Malkawi"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/18pl_a_In2J6ljx9vSnOfkUhs2zmq8KDC/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783177383407",
            "name": {
              "ar": "الأعمال الدولية",
              "en": "International Business",
              "fr": "Commerce international"
            },
            "instructors": [
              {
                "ar": "الهام الفاعوري",
                "en": "الهام الفاعوري",
                "fr": "الهام الفاعوري"
              }
            ],
            "files": [
              {
                "id": "file-1783177383407-1",
                "title": {
                  "ar": "إدارة الأعمال الدولية – د. إلهام الفاعوري – الفصول 1 إلى 4",
                  "en": "International Business Management – Dr. Ilham Al-Faouri – Chapters 1 to 4",
                  "fr": "International Business Management – Dr Ilham Al-Faouri – chapitres 1 à 4"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1HNLk9ZIhC8odWvcHbuy7eL4d68JP5bhR/view?usp=drive_link"
              },
              {
                "id": "file-1783177383407-2",
                "title": {
                  "ar": "تلخيص مادة الأعمال الدولية – الفصول 1 و2 و3 – د. إلهام الفاعوري",
                  "en": "International Business summary – Chapters 1, 2, 3 – Dr. Ilham Al-Faouri",
                  "fr": "Résumé du commerce international – chapitres 1, 2, 3 – Dr Ilham Al-Faouri"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1kqzcjsvxqufYsjBufEiO-HmJpcsoVpQK/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783177635001",
            "name": {
              "ar": "اتصالات إدارية",
              "en": "Administrative Communication",
              "fr": "Communication administrative"
            },
            "instructors": [
              {
                "ar": "يسار الشطناوي",
                "en": "يسار الشطناوي",
                "fr": "يسار الشطناوي"
              },
              {
                "ar": "علاء الرواد",
                "en": "علاء الرواد",
                "fr": "علاء الرواد"
              }
            ],
            "files": [
              {
                "id": "file-1783177635001-1",
                "title": {
                  "ar": "تلخيص مادة الاتصالات الإدارية – الفصول 1 و2 و3 و4 – د. علاء الرواد",
                  "en": "Administrative Communication summary – Chapters 1, 2, 3, 4 – Dr. Alaa Al-Rawad",
                  "fr": "Résumé de la communication administrative – chapitres 1, 2, 3, 4 – Dr Alaa Al-Rawad"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1263LExc46r709pBx4Mn8sNow2MNAoZKj/view?usp=drive_link"
              },
              {
                "id": "file-1783177635001-2",
                "title": {
                  "ar": "كويز + امتحان نهائي لمادة الاتصالات الإدارية – د. يسار شطناوي",
                  "en": "Quiz + Final exam – Administrative Communication – Dr. Yasar Shatnawi",
                  "fr": "Quiz + examen final – Communication administrative – Dr Yasar Shatnawi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1b7Ay9-I8qrYiGMRhBEmsUqViuNr4ItuN/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783177760705",
            "name": {
              "ar": "إدارة السياحة والفنادق",
              "en": "Tourism and Hotel Management",
              "fr": "Gestion du tourisme et de l’hôtellerie"
            },
            "instructors": [
              {
                "ar": "محمود النوايسة",
                "en": "محمود النوايسة",
                "fr": "محمود النوايسة"
              }
            ],
            "files": [
              {
                "id": "file-1783177760705-1",
                "title": {
                  "ar": "امتحان وكويز مادة الإدارة السياحية – د. محمود نوايسة",
                  "en": "Exam & Quiz – Tourism Management – Dr. Mahmoud Nwaisah",
                  "fr": "Examen & quiz – Gestion touristique – Dr Mahmoud Nwaisah"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1RBHpSdHL49XYX5B-kcN0256MyH5LbRig/view?usp=sharing"
              }
            ]
          },
          {
            "id": "business-admin-1783180147301",
            "name": {
              "ar": "إدارة سلسلة التزويد",
              "en": "Supply Chain Management",
              "fr": "Gestion de la chaîne d’approvisionnement"
            },
            "instructors": [
              {
                "ar": "ايمان الملكاوي",
                "en": "ايمان الملكاوي",
                "fr": "ايمان الملكاوي"
              }
            ],
            "files": [
              {
                "id": "file-1783180147301-1",
                "title": {
                  "ar": "امتحان منتصف الفصل لمادة سلسلة التزويد – د. إيمان ملكاوي",
                  "en": "Supply Chain midterm exam – Dr. Iman Malkawi",
                  "fr": "Examen de mi-session – chaîne d’approvisionnement – Dr Iman Malkawi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1GpVbIShmxR7BefWXvLlbx5Yk2eFYPYEc/view?usp=sharing"
              }
            ]
          },
          {
            "id": "business-admin-1783181033506",
            "name": {
              "ar": "إدارة الموارد البشرية",
              "en": "Human Resource Management (HRM)",
              "fr": "Gestion des ressources humaines"
            },
            "instructors": [
              {
                "ar": "الهام الفاعوري",
                "en": "الهام الفاعوري",
                "fr": "الهام الفاعوري"
              }
            ],
            "files": [
              {
                "id": "file-1783181033506-1",
                "title": {
                  "ar": "ملخص مادة إدارة الموارد البشرية – الفصول 1 و4 و5 و6 – د. إلهام الفاعوري",
                  "en": "Human Resources Management summary – Chapters 1, 4, 5, 6 – Dr. Ilham Al-Faouri",
                  "fr": "Résumé de la gestion des ressources humaines – chapitres 1, 4, 5, 6 – Dr Ilham Al-Faouri"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/18Cc9GSm95HAOAe4Bt9IZ27BB4Fk3C7Wt/view?usp=drive_link"
              },
              {
                "id": "file-1783181033506-2",
                "title": {
                  "ar": "تلخيص الفصل الثامن من مادة إدارة الموارد البشرية (الجزء 1)",
                  "en": "Summary of Chapter 8 – Human Resources Management (Part 1)",
                  "fr": "Résumé du chapitre 8 – Gestion des ressources humaines (partie 1)"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1XGVlIWSSjFYY_LCuMj6Xn4pqTrUJN3Jr/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783181255479",
            "name": {
              "ar": "إدارة المعرفة",
              "en": "Knowledge Management",
              "fr": "Gestion des connaissances"
            },
            "instructors": [
              {
                "ar": "محمود النوايسة",
                "en": "محمود النوايسة",
                "fr": "محمود النوايسة"
              },
              {
                "ar": "ايمان الملكاوي",
                "en": "ايمان الملكاوي",
                "fr": "ايمان الملكاوي"
              }
            ],
            "files": [
              {
                "id": "file-1783181255479-1",
                "title": {
                  "ar": "ملخص الفصل الثاني من إدارة المعرفة (Introduction) – د. إلهام الفاعوري + ميد د. إيمان ملكاوي",
                  "en": "Summary of Chapter 2 – Knowledge Management (Introduction) – Dr. Ilham Al-Faouri + Midterm exam – Dr. Iman Malkawi",
                  "fr": "Résumé du chapitre 2 – Gestion des connaissances (Introduction) – Dr Ilham Al-Faouri + examen de mi-session – Dr Iman Malkawi"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1ftuVsMkNKtnS9fyl3eVP2wdEeocYuiYr/view?usp=drive_link"
              },
              {
                "id": "file-1783181255479-2",
                "title": {
                  "ar": "تلخيص مادة إدارة المعرفة – الفصول 1 و2 و9 – د. محمود نوايسة",
                  "en": "Knowledge Management summary – Chapters 1, 2, 9 – Dr. Mahmoud Nwaisah",
                  "fr": "Résumé de la gestion des connaissances – chapitres 1, 2, 9 – Dr Mahmoud Nwaisah"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1rOZXE4Z0SpQ1Cesr7AgTP8XxQmwpfyin/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783181456181",
            "name": {
              "ar": "إدارة المشاريع",
              "en": "Project Management",
              "fr": "Gestion de projet"
            },
            "instructors": [
              {
                "ar": "يسار الشطناوي",
                "en": "يسار الشطناوي",
                "fr": "يسار الشطناوي"
              }
            ],
            "files": [
              {
                "id": "file-1783181456181-1",
                "title": {
                  "ar": "مجموعة من الملفات",
                  "en": "A set of files",
                  "fr": "Ensemble de fichiers"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/drive/folders/1osfmBo6BlHLg3tfZNNEHChKzJyXMwGmp?usp=sharing"
              }
            ]
          },
          {
            "id": "business-admin-1783181628084",
            "name": {
              "ar": "إدارة العمليات والإنتاج",
              "en": "Operations and Production Management",
              "fr": "Gestion des opérations et de la production"
            },
            "instructors": [
              {
                "ar": "صدام الوادي",
                "en": "صدام الوادي",
                "fr": "صدام الوادي"
              },
              {
                "ar": "محمود النوايسة",
                "en": "محمود النوايسة",
                "fr": "محمود النوايسة"
              }
            ],
            "files": [
              {
                "id": "file-1783181628084-1",
                "title": {
                  "ar": "امتحان منتصف الفصل لمادة إدارة العمليات والإنتاج – د. صدام الوادي",
                  "en": "Midterm exam – Operations and Production Management – Dr. Saddam Al-Wadi",
                  "fr": "Examen de mi-session – Gestion des opérations et de la production – Dr Saddam Al-Wadi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1eQ2hk9gMUJWdGTImaFXVbqGMf1P8tXhV/view?usp=drive_link"
              },
              {
                "id": "file-1783181628084-2",
                "title": {
                  "ar": "امتحان منتصف الفصل + كويز لمادة إدارة العمليات والإنتاج – د. محمود نوايسة",
                  "en": "Midterm + Quiz – Operations and Production Management – Dr. Mahmoud Nwaisah",
                  "fr": "Examen de mi-session + quiz – Gestion des opérations et de la production – Dr Mahmoud Nwaisah"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1XR-KtlAHh68YWZEjpm6VDwK2jI6OVUia/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "business-admin-1783181755390",
            "name": {
              "ar": "إدارة الجودة الشاملة",
              "en": "Total Quality Management (TQM)",
              "fr": "Gestion de la qualité totale"
            },
            "instructors": [
              {
                "ar": "الهام الفاعوري",
                "en": "الهام الفاعوري",
                "fr": "الهام الفاعوري"
              }
            ],
            "files": [
              {
                "id": "file-1783181755390-1",
                "title": {
                  "ar": "مجموعة من الملفات",
                  "en": "A collection of files",
                  "fr": "Un ensemble de fichiers"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/drive/folders/1HM-0M5Qbn8fy0e9GKiR5TvpNfubvyRU7?usp=sharing"
              }
            ]
          },
          {
            "id": "business-admin-1783181846462",
            "name": {
              "ar": "إدارة التسويق",
              "en": "Marketing Management",
              "fr": "Gestion du marketing"
            },
            "instructors": [
              {
                "ar": "يسار الشطناوي",
                "en": "يسار الشطناوي",
                "fr": "يسار الشطناوي"
              }
            ],
            "files": [
              {
                "id": "file-1783181846462-1",
                "title": {
                  "ar": "تلخيص مادة إدارة التسويق – الفصول 1 و3 و4 – د. يسار شطناوي + ملخص باللغة العربية",
                  "en": "Marketing Management summary – Chapters 1, 3, 4 – Dr. Yasar Shatnawi + Arabic summary",
                  "fr": "Résumé de la gestion du marketing – chapitres 1, 3, 4 – Dr Yasar Shatnawi + résumé en arabe"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1irUqiVUOcNEyaVHwADoOODtOkdtAG3OT/view?usp=sharing"
              }
            ]
          },
          {
            "id": "business-admin-1783182020600",
            "name": {
              "ar": "إدارة استراتيجية",
              "en": "Strategic Management",
              "fr": "Management stratégique"
            },
            "instructors": [
              {
                "ar": "الهام الفاعوري",
                "en": "الهام الفاعوري",
                "fr": "الهام الفاعوري"
              }
            ],
            "files": [
              {
                "id": "file-1783182020600-1",
                "title": {
                  "ar": "تلخيص مادة الإدارة الاستراتيجية – الفصول 1 و2 و5 و6 + ملخص كويز – د. إلهام الفاعوري",
                  "en": "Strategic Management summary – Chapters 1, 2, 5, 6 + quiz summary – Dr. Ilham Al-Faouri",
                  "fr": "Résumé du management stratégique – chapitres 1, 2, 5, 6 + résumé de quiz – Dr Ilham Al-Faouri"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1p7Zef6EV5Vt4n9vz8aVmXGsjMBpEbW9z/view?usp=drive_link"
              },
              {
                "id": "file-1783182020600-2",
                "title": {
                  "ar": "ملخص مادة الإدارة الاستراتيجية – الفصول 1 و2 و4 و5 و6 + كويز – د. إلهام الفاعوري",
                  "en": "Strategic Management summary – Chapters 1, 2, 4, 5, 6 + quiz – Dr. Ilham Al-Faouri",
                  "fr": "Résumé du management stratégique – chapitres 1, 2, 4, 5, 6 + quiz – Dr Ilham Al-Faouri"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1mG3xosydG46-JWh_8yIwRjvoki4Twpz6/view?usp=drive_link"
              }
            ]
          }
        ]
      },
      {
        "id": "accounting",
        "name": {
          "ar": "المحاسبة",
          "en": "Accounting",
          "fr": "Comptabilité"
        },
        "courses": [
          {
            "id": "accounting-1783182741766",
            "name": {
              "ar": "نظم المعلومات المحاسبية",
              "en": "Accounting Information Systems (AIS)",
              "fr": "Systèmes d’information comptable"
            },
            "instructors": [
              {
                "ar": "عمر السنجلاوي",
                "en": "عمر السنجلاوي",
                "fr": "عمر السنجلاوي"
              }
            ],
            "files": [
              {
                "id": "file-1783182741766-1",
                "title": {
                  "ar": "امتحان نهائي لمادة نظم المعلومات المحاسبية – د. عمر سنجلاوي",
                  "en": "Final exam – Accounting Information Systems (AIS) – Dr. Omar Snglawi",
                  "fr": "Examen final – Systèmes d’information comptable – Dr Omar Snglawi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1GoXOJMr3lgrt6hDUgdNG2JLiciTMmrij/view?usp=drive_link"
              },
              {
                "id": "file-1783182741766-2",
                "title": {
                  "ar": "امتحان منتصف الفصل لمادة نظم المعلومات المحاسبية – د. عمر السنجلاوي",
                  "en": "Midterm exam – Accounting Information Systems (AIS) – Dr. Omar Al-Snglawi",
                  "fr": "Examen de mi-session – Systèmes d’information comptable – Dr Omar Al-Snglawi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1l-Uaf2c5zwHQfdM6J9CvpogGbNjuVnzQ/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "accounting-1783182832295",
            "name": {
              "ar": "منهجية البحث في المحاسبة",
              "en": "Research Methodology in Accounting",
              "fr": "Méthodologie de recherche en comptabilité"
            },
            "instructors": [
              {
                "ar": "عمر السنجلاوي",
                "en": "عمر السنجلاوي",
                "fr": "عمر السنجلاوي"
              }
            ],
            "files": [
              {
                "id": "file-1783182832295-1",
                "title": {
                  "ar": "امتحان منتصف الفصل لمادة منهجية البحث في المحاسبة – د. عمر السنجلاوي",
                  "en": "Midterm exam – Research Methodology in Accounting – Dr. Omar Al-Snglawi",
                  "fr": "Examen de mi-session – Méthodologie de recherche en comptabilité – Dr Omar Al-Snglawi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/129oVdIyW28ISYLHKHNFb4cU3s-J29EIb/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "accounting-1783183016865",
            "name": {
              "ar": "معايير التدقيق الدولية",
              "en": "International Standards on Auditing (ISA)",
              "fr": "Normes internationales d’audit"
            },
            "instructors": [
              {
                "ar": "عمر حواتمة",
                "en": "عمر حواتمة",
                "fr": "عمر حواتمة"
              }
            ],
            "files": [
              {
                "id": "file-1783183016865-1",
                "title": {
                  "ar": "معايير التدقيق – د. عمر حواتمة",
                  "en": "Auditing Standards – Dr. Omar Hawatmeh",
                  "fr": "Normes d’audit – Dr Omar Hawatmeh"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1mhEduFhjxz3_iIusEvYhcKQOl-i-Ialp/view?usp=drive_link"
              },
              {
                "id": "file-1783183016865-2",
                "title": {
                  "ar": "معايير التدقيق",
                  "en": "Auditing Standards",
                  "fr": "Normes d’audit"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1cQ1ti5JfFE690ao4DKTkTRaZIL3T06F2/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "accounting-1783183247941",
            "name": {
              "ar": "محاسبة متقدمة",
              "en": "Advanced Accounting",
              "fr": "Comptabilité avancée"
            },
            "instructors": [
              {
                "ar": "عمر السنجلاوي",
                "en": "عمر السنجلاوي",
                "fr": "عمر السنجلاوي"
              }
            ],
            "files": [
              {
                "id": "file-1783183247941-1",
                "title": {
                  "ar": "امتحان نهائي لمادة المحاسبة المتقدمة – د. عمر السنجلاوي",
                  "en": "Final exam – Advanced Accounting – Dr. Omar Al-Snglawi",
                  "fr": "Examen final – Comptabilité avancée – Dr Omar Al-Snglawi"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/17IOXWLDWCCDkynFsUXK8p7htSiOraHyA/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "accounting-1783183890798",
            "name": {
              "ar": "محاسبة مالية خاصة",
              "en": "Special Financial Accounting",
              "fr": "Comptabilité financière spéciale"
            },
            "instructors": [
              {
                "ar": "موسى الدوايسة",
                "en": "موسى الدوايسة",
                "fr": "موسى الدوايسة"
              }
            ],
            "files": [
              {
                "id": "file-1783183890798-1",
                "title": {
                  "ar": "امتحان منتصف الفصل لمادة المحاسبة المالية الخاصة – د. موسى النوايسة – نموذجين",
                  "en": "Midterm exam – Special Financial Accounting – Dr. Musa Al-Nwaisah – Two versions",
                  "fr": "Examen de mi-session – Comptabilité financière spéciale – Dr Mousa Al-Nwaisah – Deux versions"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1I9izdI-bYl1LuUlaqAnvJAgJONgtpTbb/view?usp=drive_link"
              },
              {
                "id": "file-1783183890798-2",
                "title": {
                  "ar": "محاسبة المنشآت المالية الخاصة – د. حواتمة",
                  "en": "Accounting for Special Financial Institutions – Dr. Hawatmeh",
                  "fr": "Comptabilité des établissements financiers spéciaux – Dr Hawatmeh"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1dHlSuMM9nRCPB-4bk7bvrs72Np-arR18/view?usp=drive_link"
              },
              {
                "id": "file-1783183890798-3",
                "title": {
                  "ar": "تلخيص مادة المحاسبة المالية الخاصة + أسئلة كويز وميد – د. موسى النوايسة",
                  "en": "Special Financial Accounting summary + quiz & midterm questions – Dr. Musa Al-Nwaisah",
                  "fr": "Résumé de la comptabilité financière spéciale + questions de quiz et de mi-session – Dr Mousa Al-Nwaisah"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1jJSHheGjY8xi_b1dB5DBOY3RnovWOr5v/view?usp=drive_link"
              }
            ]
          },
          {
            "id": "accounting-1783184174939",
            "name": {
              "ar": "محاسبة دولية",
              "en": "International Accounting",
              "fr": "Comptabilité internationale"
            },
            "instructors": [
              {
                "ar": "محمد العدوان",
                "en": "محمد العدوان",
                "fr": "محمد العدوان"
              }
            ],
            "files": [
              {
                "id": "file-1783184174939-1",
                "title": {
                  "ar": "امتحان منتصف الفصل لمادة المحاسبة الدولية",
                  "en": "Midterm exam – International Accounting",
                  "fr": "Examen de mi-session – Comptabilité internationale"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/18AX5tc1jkGgdgVMlYgS_pprCzlvwpyuZ/view?usp=drive_link"
              },
              {
                "id": "file-1783184174939-2",
                "title": {
                  "ar": "ملخص مادة المحاسبة الدولية – د. محمد العدوان",
                  "en": "International Accounting summary – Dr. Mohammad Al-Adwan",
                  "fr": "Résumé de la comptabilité internationale – Dr Mohammad Al-Adwan"
                },
                "type": "summary",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1AkvPWNFzHhLRYO4jAkQe71naA0Qf65Eo/view?usp=drive_link"
              },
              {
                "id": "file-1783184174939-3",
                "title": {
                  "ar": "امتحان نهائي لمادة المحاسبة الدولية – د. رانيا",
                  "en": "Final exam – International Accounting – Dr. Rania",
                  "fr": "Examen final – Comptabilité internationale – Dr Rania"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1KMgvWujXJWG5Z51M6OimzhGbeJ9PTLpF/view?usp=drive_link"
              },
              {
                "id": "file-1783184174939-4",
                "title": {
                  "ar": "امتحان نهائي لمادة المحاسبة الدولية – د. محمد العدوان",
                  "en": "Final exam – International Accounting – Dr. Mohammad Al-Adwan",
                  "fr": "Examen final – Comptabilité internationale – Dr Mohammad Al-Adwan"
                },
                "type": "testbank",
                "preparedBy": null,
                "path": "https://drive.google.com/file/d/1GFxv6s9ajy6ZTHsrjIVGJa2aiIISKFgW/view?usp=drive_link"
              }
            ]
          }
        ]
      },
      {
        "id": "finance",
        "name": {
          "ar": "التمويل",
          "en": "Finance",
          "fr": "Finance"
        },
        "courses": []
      }
    ]
  },
  {
    "id": "tourism",
    "name": {
      "ar": "كلية السياحة والفندقة",
      "en": "College of Tourism & Hospitality",
      "fr": "Faculté du Tourisme et de l'Hôtellerie"
    },
    "icon": "🏨",
    "color": "#0891b2",
    "specializations": [
      {
        "id": "tourism-management",
        "name": {
          "ar": "الإدارة السياحية",
          "en": "Tourism Management",
          "fr": "Gestion du Tourisme"
        },
        "courses": []
      },
      {
        "id": "hotel-management",
        "name": {
          "ar": "الإدارة الفندقية",
          "en": "Hotel Management",
          "fr": "Gestion Hôtelière"
        },
        "courses": []
      }
    ]
  },
  {
    "id": "languages",
    "name": {
      "ar": "كلية اللغات",
      "en": "College of Languages",
      "fr": "Faculté des Langues"
    },
    "icon": "📚",
    "color": "#7c3aed",
    "specializations": [
      {
        "id": "english-literature",
        "name": {
          "ar": "اللغة الإنجليزية وآدابها",
          "en": "English Language & Literature",
          "fr": "Langue et Littérature Anglaises"
        },
        "courses": []
      },
      {
        "id": "english-translation",
        "name": {
          "ar": "اللغة الإنجليزية/الترجمة",
          "en": "English / Translation",
          "fr": "Anglais / Traduction"
        },
        "courses": []
      },
      {
        "id": "french-english",
        "name": {
          "ar": "اللغة الفرنسية والإنجليزية",
          "en": "French and English",
          "fr": "Français et Anglais"
        },
        "courses": []
      }
    ]
  },
  {
    "id": "law",
    "name": {
      "ar": "كلية الحقوق",
      "en": "College of Law",
      "fr": "Faculté de Droit"
    },
    "icon": "⚖️",
    "color": "#b45309",
    "specializations": [
      {
        "id": "law-specialization",
        "name": {
          "ar": "القانون",
          "en": "Law",
          "fr": "Droit"
        },
        "courses": []
      }
    ]
  },
  {
    "id": "sciences",
    "name": {
      "ar": "كلية العلوم الأساسية والبحرية",
      "en": "College of Basic & Marine Sciences",
      "fr": "Faculté des Sciences Fondamentales et Marines"
    },
    "icon": "🔬",
    "color": "#059669",
    "specializations": [
      {
        "id": "mathematics",
        "name": {
          "ar": "الرياضيات",
          "en": "Mathematics",
          "fr": "Mathématiques"
        },
        "courses": []
      },
      {
        "id": "life-sciences",
        "name": {
          "ar": "العلوم الحياتية",
          "en": "Life Sciences",
          "fr": "Sciences de la Vie"
        },
        "courses": []
      }
    ]
  },
  {
    "id": "it",
    "name": {
      "ar": "كلية نظم وتكنولوجيا المعلومات",
      "en": "College of Information Technology",
      "fr": "Faculté des Technologies de l'Information"
    },
    "icon": "💻",
    "color": "#dc2626",
    "specializations": [
      {
        "id": "business-it",
        "name": {
          "ar": "تكنولوجيا معلومات الأعمال",
          "en": "Business Information Technology",
          "fr": "Technologies de l'Information des Affaires"
        },
        "courses": []
      },
      {
        "id": "cybersecurity",
        "name": {
          "ar": "الأمن السيبراني",
          "en": "Cybersecurity",
          "fr": "Cybersécurité"
        },
        "courses": []
      },
      {
        "id": "computer-information-systems",
        "name": {
          "ar": "نظم المعلومات الحاسوبية",
          "en": "Computer Information Systems",
          "fr": "Systèmes d'Information Informatiques"
        },
        "courses": []
      }
    ]
  },
  {
    "id": "nursing",
    "name": {
      "ar": "كلية التمريض",
      "en": "College of Nursing",
      "fr": "Faculté des Sciences Infirmières"
    },
    "icon": "🏥",
    "color": "#be185d",
    "specializations": [
      {
        "id": "nursing-specialization",
        "name": {
          "ar": "التمريض",
          "en": "Nursing",
          "fr": "Sciences Infirmières"
        },
        "courses": []
      }
    ]
  }
];

// ==========================================
// Helper functions
// ==========================================

function findCollege(collegeId) {
  return collegesData.find((c) => c.id === collegeId) || null;
}

function findSpecialization(collegeId, specId) {
  const college = findCollege(collegeId);
  if (!college) return null;
  return college.specializations.find((s) => s.id === specId) || null;
}

function findCourse(collegeId, specId, courseId) {
  const spec = findSpecialization(collegeId, specId);
  if (!spec) return null;
  return spec.courses.find((c) => c.id === courseId) || null;
}

function searchData(query, lang) {
  const results = [];
  const q = query.toLowerCase().trim();
  if (!q) return results;

  for (const college of collegesData) {
    const collegeName = getName(college.name, lang).toLowerCase();
    for (const spec of college.specializations) {
      const specName = getName(spec.name, lang).toLowerCase();
      for (const course of spec.courses) {
        const courseName = getName(course.name, lang).toLowerCase();
        const instructorMatch = course.instructors.some((instr) =>
          getName(instr, lang).toLowerCase().includes(q)
        );
        const fileMatch = course.files.some(
          (f) =>
            getName(f.title, lang).toLowerCase().includes(q) ||
            (f.preparedBy && getName(f.preparedBy, lang).toLowerCase().includes(q))
        );

        if (collegeName.includes(q) || specName.includes(q) || courseName.includes(q) || instructorMatch || fileMatch) {
          results.push({ college, specialization: spec, course });
        }
      }
    }
  }
  return results;
}
